// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLTNRpijiE3wg_spUrG9wtF_RX6lspdVY',
    appId: '1:348557725346:web:9f254e69186c3c72f4d1fb',
    messagingSenderId: '348557725346',
    projectId: 'drawpaint-42457',
    authDomain: 'drawpaint-42457.firebaseapp.com',
    storageBucket: 'drawpaint-42457.firebasestorage.app',
    measurementId: 'G-JY1LDX147V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEuB8nb73kWQiZmp6Y5LLG8wrNB4lpSIk',
    appId: '1:348557725346:android:dc0f9122983581f0f4d1fb',
    messagingSenderId: '348557725346',
    projectId: 'drawpaint-42457',
    storageBucket: 'drawpaint-42457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1UiGasU6HEyLvUYX-cZpG5X6p4CN98Q',
    appId: '1:348557725346:ios:d4784bd6ba84c670f4d1fb',
    messagingSenderId: '348557725346',
    projectId: 'drawpaint-42457',
    storageBucket: 'drawpaint-42457.firebasestorage.app',
    iosBundleId: 'com.example.draw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1UiGasU6HEyLvUYX-cZpG5X6p4CN98Q',
    appId: '1:348557725346:ios:d4784bd6ba84c670f4d1fb',
    messagingSenderId: '348557725346',
    projectId: 'drawpaint-42457',
    storageBucket: 'drawpaint-42457.firebasestorage.app',
    iosBundleId: 'com.example.draw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLTNRpijiE3wg_spUrG9wtF_RX6lspdVY',
    appId: '1:348557725346:web:227e3ab74bc48e6cf4d1fb',
    messagingSenderId: '348557725346',
    projectId: 'drawpaint-42457',
    authDomain: 'drawpaint-42457.firebaseapp.com',
    storageBucket: 'drawpaint-42457.firebasestorage.app',
    measurementId: 'G-6XYL92J2MJ',
  );

}